### ISSUE TITLE
Source? 

### ISSUE THREAD

**Issue by tonydavis629** [Violet24K/SpherE#1]
Hi, any plans to publish the source?

**Comment by Violet24K** [comment]
Hi Tony,

Thanks for your attention to our research work! **The code is expected to be released by July 7th.** Once the code base is uploaded, I will close this issue so that you'll receive a notification.

Recently, besides my internship, I got busy with proceedings, registration, slides, and a poster (with the GitHub link, so we have to finish this repo before the conference next month).  For this project, I'm working to create a well-documented easy-to-use benchmark repo for set retrieval, which requires much revision and clean-up of the code we submitted.

Best regards,
Zihao

**Comment by Violet24K** [comment]
Closing this issue as the first version of source is published. We warmly welcome suggestions/contributions from the community.
